import ContactMe from "@/components/contact/ContactMe";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact | Joujoniki",
  description: "Generated by create next app",
};

const ContactPage = () => {

  return (
    <ContactMe/>
  );
};

export default ContactPage;
