import AboutMe from "@/components/about/AboutMe";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "About | Joujoniki",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <AboutMe/>
  );
};

export default AboutPage;
