import type { Metadata } from "next";
import "./globals.css";
import { Sora } from 'next/font/google'
import StoreProvider from "./storeProvider";

const sora = Sora({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} antialiased` }
      >
       <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
