import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./font";
import { Toaster } from "sonner";
import ClientOnly from "@/components/ClientOnly";
import StoreProvider from "./storeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${roboto.className} antialiased  min-h-screen`}>
    <StoreProvider>
      <ClientOnly>
          <Toaster />
          {children}
      </ClientOnly>
      </StoreProvider>
      </body>
    </html>
  );
}
