import type { Metadata } from "next";
import dynamic from 'next/dynamic';
import BaseContainer from "@/components/shared/BaseContainer";
import ClientOnly from "@/components/ClientOnly";
import ContactMeHome from "@/components/contact/ContactMeHome";
import Footer from "@/components/shared/Footer";
// Dynamically import components that might use browser APIs
const Banner = dynamic(() => import("@/components/home/Banner"), { ssr: true });
const Skills = dynamic(() => import("@/components/home/Skills"), { ssr: true });
const FeaturedProjects = dynamic(() => import("@/components/home/FeaturedProjects"), { ssr: true });

export const metadata: Metadata = {
  title: "Home | Joujoniki",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <ClientOnly>
      <div className="">
        <div className="w-full absolute top-0 left-0">
          <Banner />
          <BaseContainer>
            <>
              <Skills />
              <FeaturedProjects />
              <ContactMeHome/>
              <Footer/>
            </>
          </BaseContainer>
        </div>
      </div>
    </ClientOnly>
  );
}