import type { Metadata } from "next";
import Banner from "@/components/home/Banner";
import FeaturedProjects from "@/components/home/FeaturedProjects";
import Skills from "@/components/home/Skills";

export const metadata: Metadata = {
  title: "Home | Joujoniki",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
      <Banner/>
      <Skills/>
      <FeaturedProjects/>
    </div>
  );
}
